# Generated by Django 4.1.5 on 2023-03-03 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedo', '0002_feedo_direct_report'),
        ('client', '0002_clientcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='epfm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Feedo.feedo'),
        ),
    ]
