# Generated by Django 4.1.5 on 2023-03-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_epfm'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='escalation',
            field=models.BooleanField(default=False),
        ),
    ]
