# Generated by Django 4.1.5 on 2023-03-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_client_logo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='next_monthly_sync',
            field=models.DateField(blank=True, null=True),
        ),
    ]
