# Generated by Django 4.1.5 on 2023-03-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_next_monthly_sync'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='next_monthly_sync',
            new_name='next_recurring_sync',
        ),
        migrations.AddField(
            model_name='client',
            name='recurring_sync_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
