# Generated by Django 4.1.5 on 2023-03-03 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedo',
            name='direct_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Feedo.feedo'),
        ),
    ]
