# Generated by Django 4.1.5 on 2023-03-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedo', '0002_feedo_direct_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedo',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
