# Generated by Django 4.1.5 on 2023-01-13 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('task', '0002_task_related_project_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='related_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
            preserve_default=False,
        ),
    ]
