# Generated by Django 4.1.5 on 2023-01-17 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('task', '0003_task_related_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
