# Generated by Django 4.1.5 on 2023-01-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('task', '0005_alter_task_related_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='client.client'),
        ),
    ]
