# Generated by Django 4.1.5 on 2023-02-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_related_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ticket_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
