# Generated by Django 4.1.5 on 2023-03-06 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedo', '0002_feedo_direct_report'),
        ('task', '0009_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='related_client_epfm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_feedo', to='Feedo.feedo'),
        ),
    ]
