# Generated by Django 4.1.5 on 2023-02-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_alter_update_related_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='related_task',
        ),
    ]
