# Generated by Django 4.1.5 on 2023-02-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_update_related_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='status',
            field=models.CharField(choices=[('task_updated', 'Task Update'), ('task_completed', 'Task Completed'), ('task_delayed', 'Task Delayed'), ('task_created', 'Task Created'), ('question_posted', 'Question Posted'), ('question_answered', 'Question Answered'), ('new_project_created', 'New Project Created'), ('project_completed', 'Project Completed'), ('project_delayed', 'Project Delayed'), ('new_promotion', 'New Promotion'), ('promotion_issue', 'Promotion Issue'), ('document_posted', 'Document Posted'), ('video_posted', 'Video Posted'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
