# Generated by Django 4.1.5 on 2023-02-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0006_update_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='status',
            new_name='update_type',
        ),
    ]
