# Generated by Django 4.1.5 on 2023-02-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0007_rename_status_update_update_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_type',
            field=models.CharField(choices=[('Task Update', 'Task Update'), ('Task Completed', 'Task Completed'), ('Task Delayed', 'Task Delayed'), ('Task Created', 'Task Created'), ('Question Posted', 'Question Posted'), ('Question Answered', 'Question Answered'), ('New Project Created', 'New Project Created'), ('Project Completed', 'Project Completed'), ('Project Delayed', 'Project Delayed'), ('New Promotion', 'New Promotion'), ('Promotion Issue', 'Promotion Issue'), ('Promotion Update', 'Promotion Update'), ('Document Posted', 'Document Posted'), ('Video Posted', 'Video Posted'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
