# Generated by Django 4.1.5 on 2023-03-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0009_alter_update_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
