# Generated by Django 4.1.5 on 2023-03-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0011_update_ticket_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='ticket_link',
        ),
    ]
