# Generated by Django 4.1.5 on 2023-01-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('Todo', 'Todo'), ('Complete', 'Complete'), ('On Hold', 'On Hold')], default='Todo', max_length=50)),
                ('client_visible', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
            ],
        ),
    ]
