# Generated by Django 4.1.5 on 2023-01-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectitem_related_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
    ]
