# Generated by Django 4.1.5 on 2023-01-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('project', '0004_alter_projectitem_related_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
            preserve_default=False,
        ),
    ]
